######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 10 14:19:55 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += ../rtcore/ 
LIBS += -L../rtcore/ -lrtcore
QMAKE_CXXFLAGS += -O3 -DNDEBUG -g

# Input
HEADERS += ra2parser.h
SOURCES += ra2parser.cpp rtstatic.cpp
